import type { Metadata } from "next";
import localFont from 'next/font/local'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: '../../public/fonts/Degular-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Degular-Semibold.otf',
      weight: '600',
      style: 'semibold',
    },
  ],
  variable: '--font-main',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={myFont.variable}
      >
        <div className="flex items-center pt-[30px] fixed z-999">
          <Link href='/' className="ml-[125px] cursor-pointer z-10">
            <Image src='/logo.svg' alt='Logo Scenium' width={115} height={44} />
          </Link>
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
