import type { Metadata } from "next";
import localFont from 'next/font/local'
import Navbar from "@/components/Navbar";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: '../../public/fonts/Degular-Thin.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-main',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={myFont.variable}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
